version: '3.2'
services:
  amigosecretodb:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  amigosecretoweb:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: uwsgi --http :8000 --ini uwsgi.ini --thunder-lock
    ports:
      - "8112:8000"
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - amigosecretodb
