# Generated by Django 3.2.16 on 2022-12-20 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(default='xwusio', max_length=20)),
                ('desired_gift', models.CharField(max_length=200, null=True)),
                ('secret_friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.friend')),
            ],
        ),
    ]
