# Generated by Django 3.2.16 on 2022-12-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='password',
            field=models.CharField(default='zaxdor', max_length=20),
        ),
    ]
