# Generated by Django 3.2.16 on 2022-12-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221220_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='password',
            field=models.CharField(default='gdzfog', max_length=20),
        ),
    ]
