# Generated by Django 3.2.16 on 2022-12-20 04:54

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_friend_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='password',
            field=models.CharField(default=home.models.rand_str, max_length=20),
        ),
    ]
